# Generated by Django 3.2.9 on 2021-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=55, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=55, verbose_name='Фамилия')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Почта')),
                ('login', models.CharField(db_index=True, max_length=55, verbose_name='Логин')),
                ('password', models.CharField(db_index=True, max_length=55, verbose_name='Пароль')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
