# Generated by Django 3.2.9 on 2021-11-14 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0002_data_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('login',)},
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='da', to=settings.AUTH_USER_MODEL),
        ),
    ]
